import { Country } from './country-lookup';

export const countryAliases: Record<string, string> = {
    'Bahamas, The': 'Bahamas',
    Bolivia: 'Bolivia (Plurinational State of)',
    Brunei: 'Brunei Darussalam',
    'Cape Verde': 'Cabo Verde',
    'Congo (Brazzaville)': 'Congo',
    'Congo (Kinshasa)': 'Congo, Democratic Republic of the',
    "Cote d'Ivoire": "Côte d'Ivoire",
    'Ivory Coast': "Côte d'Ivoire",
    'Cruise Ship': 'No Country',
    'Diamond Princess': 'No Country',
    'East Timor': 'Timor-Leste',
    'Gambia, The': 'Gambia',
    Iran: 'Iran (Islamic Republic of)',
    'Korea, South': 'Korea, Republic of',
    'South Korea': 'Korea, Republic of',
    Moldova: 'Moldova, Republic of',
    'Republic of the Congo': 'Congo',
    Reunion: 'Réunion',
    Russia: 'Russian Federation',
    Syria: 'Syrian Arab Republic',
    'Taiwan*': 'Taiwan, Province of China',
    Tanzania: 'Tanzania, United Republic of',
    'The Bahamas': 'Bahamas',
    'The Gambia': 'Gambia',
    'United Kingdom': 'United Kingdom of Great Britain and Northern Ireland',
    US: 'United States of America',
    Venezuela: 'Venezuela (Bolivarian Republic of)',
    Vietnam: 'Viet Nam',
    'Mainland China': 'China',
    Taiwan: 'Taiwan, Province of China',
};

export const missingCountries: Country[] = [
    { name: 'Kosovo', code: 'XK', region: 'Europe', subRegion: 'Southern Europe' },
    { name: 'No Country', code: 'NONE', region: 'None', subRegion: 'None' },
    { name: 'Macau', code: 'MO', region: 'Asia', subRegion: 'Eastern Asia' },
    { name: 'Laos', code: 'LA', region: 'Asia', subRegion: 'South-eastern Asia' },
];
